export const tableTranslations: Record<string, string> = {
  "members": "Anagrafica e Profilo",
  "payments": "Pagamenti e Ricevute",
  "courses": "Corsi e Attività",
  "memberships": "Tessere Associative",
  "companyAgreements": "Convenzioni Aziendali",
  "memberDiscounts": "Sconti Utente",
  "teamMonthlyReports": "Report Mensili Team",
  "promoRules": "Regole Promozionali",
  "carnetWallets": "Carnet / Pacchetti Ingressi",
  "pricingRules": "Regole di Prezzo",
  "instructorAgreements": "Contratti Insegnanti",
  "strategicEvents": "Programmazione Strategica",
  "studioBookings": "Prenotazioni Sale",
  "users": "Utenti di Sistema (Login)",
  "enrollments": "Iscrizioni (Link Membro-Corso)",
  "journalEntries": "Prima Nota Contabile",
  "staffRates": "Tariffe Staff",
  "activities": "Calendario Attività Singole",
  "priceMatrix": "Matrice Prezzi",
  "staffSostituzioni": "Sostituzioni Staff",
  "teamLeaveRequests": "Richieste Ferie/Permessi Team",
  "teamShiftDiaryEntries": "Diario Turni Team",
  "gemConversations": "Conversazioni Messaggistica",
  "gemMessages": "Messaggi",
  "memberFormsSubmissions": "Moduli Compilati Utenti",
  "memberUploads": "Caricamenti Documenti Utenti",
  "payslips": "Buste Paga",
  "studios": "Sale e Spazi",
  "teamEmployees": "Dipendenti Team",
  "teamNotes": "Note Team",
  "customReports": "Custom Reports",
  "memberPackages": "Member Packages",
  "staffDisciplinaryLog": "Staff Disciplinary Log",
  "staffPresenze": "Staff Presenze",
  "teamAttendanceLogs": "Team Attendance Logs",
  "teamDocumentVersions": "Team Document Versions",
  "teamScheduledShifts": "Team Scheduled Shifts",
  "webhookLogs": "Webhook Logs",
  "welfareProviders": "Welfare Providers",
  "accountingPeriods": "Accounting Periods",
  "attendances": "Attendances",
  "carnetSessions": "Carnet Sessions",
  "courseQuotesGrid": "Course Quotes Grid",
  "globalEnrollments": "Global Enrollments",
  "teamComments": "Team Comments",
  "teamEmployeeActivityLog": "Team Employee Activity Log",
  "aiUsageLogs": "Ai Usage Logs",
  "medicalCertificates": "Medical Certificates",
  "pagodilTiers": "Pagodil Tiers",
  "teamDocuments": "Team Documents",
  "teamShiftTemplates": "Team Shift Templates",
  "teamShifts": "Team Shifts",
  "bookingServices": "Booking Services",
  "priceLists": "Price Lists",
  "quotes": "Quotes",
  "seasons": "Seasons",
  "staffContractsCompliance": "Staff Contracts Compliance",
  "staffDocumentSignatures": "Staff Document Signatures",
  "teamCheckinEvents": "Team Checkin Events",
  "teamDocumentAlerts": "Team Document Alerts",
  "teamNotifications": "Team Notifications",
  "userActivityLogs": "User Activity Logs",
  "userSessionSegments": "User Session Segments",
  "accessLogs": "Access Logs",
  "auditLogs": "Audit Logs",
  "costCenters": "Cost Centers",
  "customLists": "Custom Lists",
  "importConfigs": "Import Configs",
  "notifications": "Notifications",
  "priceListItems": "Price List Items",
  "teamActivityTypes": "Team Activity Types",
  "teamPostazioni": "Team Postazioni",
  "teamWeekAssignments": "Team Week Assignments",
  "tenants": "Tenants",
  "todos": "Todos",
  "activityStatuses": "Activity Statuses",
  "agreementMonthlyOverrides": "Agreement Monthly Overrides",
  "customListItems": "Custom List Items",
  "enrollmentDetails": "Enrollment Details",
  "knowledge": "Knowledge",
  "messages": "Messages",
  "participantTypes": "Participant Types",
  "paymentMethods": "Payment Methods",
  "paymentNotes": "Payment Notes",
  "userRoles": "User Roles",
  "cities": "Cities",
  "memberDuplicateExclusions": "Member Duplicate Exclusions",
  "memberRelationships": "Member Relationships",
  "provinces": "Provinces",
  "subscriptionTypes": "Subscription Types",
  "countries": "Countries",
  "systemConfigs": "System Configs",
  "sessions": "Sessions",
};

export const columnMappings: Record<string, Record<string, { label: string, location: string }>> = {
  "members": {
    "active": { label: "Stato Attivo", location: "Badge Intestazione" },
    "address": { label: "Indirizzo", location: "TabAnagrafica > Residenza" },
    "adminNotes": { label: "Admin Notes", location: "In App / Relazionale" },
    "alboDataIscrizione": { label: "Albo Data Iscrizione", location: "In App / Relazionale" },
    "alboNumero": { label: "Numero Albo", location: "TabAnagrafica > Accordion Professionale" },
    "alboSezione": { label: "Albo Sezione", location: "In App / Relazionale" },
    "alboTipo": { label: "Albo Tipo", location: "In App / Relazionale" },
    "alias": { label: "Alias", location: "In App / Relazionale" },
    "athenaGroup": { label: "Athena Group", location: "In App / Relazionale" },
    "athenaId": { label: "Athena  ID", location: "In App / Relazionale" },
    "athenaMemberType": { label: "Athena Member Type", location: "In App / Relazionale" },
    "attachmentMetadata": { label: "Attachment Metadata", location: "In App / Relazionale" },
    "bankName": { label: "Bank Name", location: "In App / Relazionale" },
    "bio": { label: "Bio", location: "In App / Relazionale" },
    "birthNation": { label: "Birth Nation", location: "In App / Relazionale" },
    "birthProvince": { label: "Birth Province", location: "In App / Relazionale" },
    "cancellationDate": { label: "Cancellation Date", location: "In App / Relazionale" },
    "carPlate": { label: "Car Plate", location: "In App / Relazionale" },
    "cardExpiryDate": { label: "Card Expiry Date", location: "In App / Relazionale" },
    "cardIssueDate": { label: "Card Issue Date", location: "In App / Relazionale" },
    "cardNumber": { label: "Card Number", location: "In App / Relazionale" },
    "categoryId": { label: "Category  ID", location: "In App / Relazionale" },
    "certificatoMedicoMetadata": { label: "Certificato Medico Metadata", location: "In App / Relazionale" },
    "city": { label: "Città", location: "TabAnagrafica > Residenza" },
    "codiceCatastale": { label: "Codice Catastale", location: "In App / Relazionale" },
    "codiceFe": { label: "Codice SDI", location: "TabAnagrafica > Accordion Fatturazione" },
    "companyAddress": { label: "Company Address", location: "In App / Relazionale" },
    "companyCap": { label: "Company Cap", location: "In App / Relazionale" },
    "companyCity": { label: "Company City", location: "In App / Relazionale" },
    "companyEmail": { label: "Company Email", location: "In App / Relazionale" },
    "companyFiscalCode": { label: "Company Fiscal Code", location: "In App / Relazionale" },
    "companyName": { label: "Ragione Sociale", location: "TabAnagrafica > Accordion Fatturazione" },
    "companyPhone": { label: "Company Phone", location: "In App / Relazionale" },
    "companyProvince": { label: "Company Province", location: "In App / Relazionale" },
    "consentCertificate": { label: "Consent Certificate", location: "In App / Relazionale" },
    "consentImage": { label: "Consent Image", location: "In App / Relazionale" },
    "consentMarketing": { label: "Consent Marketing", location: "In App / Relazionale" },
    "consentModule": { label: "Consent Module", location: "In App / Relazionale" },
    "consentNewsletter": { label: "Consent Newsletter", location: "In App / Relazionale" },
    "consentSms": { label: "Consent Sms", location: "In App / Relazionale" },
    "country": { label: "Country", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "createdBy": { label: "Created By", location: "In App / Relazionale" },
    "crmProfileLevel": { label: "Crm Profile Level", location: "In App / Relazionale" },
    "crmProfileOverride": { label: "Crm Profile Override", location: "In App / Relazionale" },
    "crmProfileReason": { label: "Crm Profile Reason", location: "In App / Relazionale" },
    "crmProfileScore": { label: "Crm Profile Score", location: "In App / Relazionale" },
    "dataQualityFlag": { label: "Data Quality Flag", location: "In App / Relazionale" },
    "dateOfBirth": { label: "Data di Nascita", location: "TabAnagrafica > Dati Personali" },
    "detractionModelRequested": { label: "Detraction Model Requested", location: "In App / Relazionale" },
    "detractionModelYear": { label: "Detraction Model Year", location: "In App / Relazionale" },
    "documentExpiry": { label: "Document Expiry", location: "In App / Relazionale" },
    "documentIssueDate": { label: "Document Issue Date", location: "In App / Relazionale" },
    "documentIssuedBy": { label: "Document Issued By", location: "In App / Relazionale" },
    "documentType": { label: "Document Type", location: "In App / Relazionale" },
    "driveFolderUrl": { label: "Drive Folder Url", location: "In App / Relazionale" },
    "educationDate": { label: "Education Date", location: "In App / Relazionale" },
    "educationInstitute": { label: "Education Institute", location: "In App / Relazionale" },
    "educationTitle": { label: "Education Title", location: "In App / Relazionale" },
    "email": { label: "Email Principale", location: "TabAnagrafica > Contatti" },
    "emailPec": { label: "PEC", location: "TabAnagrafica > Accordion Fatturazione" },
    "emergencyContact1Email": { label: "Emergency Contact1 Email", location: "In App / Relazionale" },
    "emergencyContact1Name": { label: "Nome Emergenza 1", location: "TabAnagrafica > Accordion Emergenza" },
    "emergencyContact1Phone": { label: "Telefono Emergenza 1", location: "TabAnagrafica > Accordion Emergenza" },
    "emergencyContact2Email": { label: "Emergency Contact2 Email", location: "In App / Relazionale" },
    "emergencyContact2Name": { label: "Emergency Contact2 Name", location: "In App / Relazionale" },
    "emergencyContact2Phone": { label: "Emergency Contact2 Phone", location: "In App / Relazionale" },
    "emergencyContact3Email": { label: "Emergency Contact3 Email", location: "In App / Relazionale" },
    "emergencyContact3Name": { label: "Emergency Contact3 Name", location: "In App / Relazionale" },
    "emergencyContact3Phone": { label: "Emergency Contact3 Phone", location: "In App / Relazionale" },
    "enrollmentStatus": { label: "Enrollment Status", location: "In App / Relazionale" },
    "entityCardExpiryDate": { label: "Entity Card Expiry Date", location: "In App / Relazionale" },
    "entityCardIssueDate": { label: "Entity Card Issue Date", location: "In App / Relazionale" },
    "entityCardNumber": { label: "Entity Card Number", location: "In App / Relazionale" },
    "entityCardType": { label: "Entity Card Type", location: "In App / Relazionale" },
    "familyCode": { label: "Family Code", location: "In App / Relazionale" },
    "fatherBirthDate": { label: "Father Birth Date", location: "In App / Relazionale" },
    "fatherBirthPlace": { label: "Father Birth Place", location: "In App / Relazionale" },
    "fatherBirthProvince": { label: "Father Birth Province", location: "In App / Relazionale" },
    "fatherCity": { label: "Father City", location: "In App / Relazionale" },
    "fatherEmail": { label: "Father Email", location: "In App / Relazionale" },
    "fatherFirstName": { label: "Father First Name", location: "In App / Relazionale" },
    "fatherFiscalCode": { label: "Father Fiscal Code", location: "In App / Relazionale" },
    "fatherLastName": { label: "Father Last Name", location: "In App / Relazionale" },
    "fatherMobile": { label: "Father Mobile", location: "In App / Relazionale" },
    "fatherPhone": { label: "Father Phone", location: "In App / Relazionale" },
    "fatherPostalCode": { label: "Father Postal Code", location: "In App / Relazionale" },
    "fatherProvince": { label: "Father Province", location: "In App / Relazionale" },
    "fatherStreetAddress": { label: "Father Street Address", location: "In App / Relazionale" },
    "fatturaFatta": { label: "Fattura Fatta", location: "In App / Relazionale" },
    "firstEnrollmentDate": { label: "First Enrollment Date", location: "In App / Relazionale" },
    "firstName": { label: "Nome", location: "TabAnagrafica > Dati Personali" },
    "fiscalCode": { label: "Codice Fiscale", location: "TabAnagrafica > Dati Personali" },
    "foodAlerts": { label: "Food Alerts", location: "In App / Relazionale" },
    "fromWhere": { label: "From Where", location: "In App / Relazionale" },
    "gender": { label: "Sesso", location: "TabAnagrafica > Dati Personali" },
    "giftMetadata": { label: "Gift Metadata", location: "In App / Relazionale" },
    "hasMedicalCertificate": { label: "Has Medical Certificate", location: "In App / Relazionale" },
    "healthNotes": { label: "Health Notes", location: "In App / Relazionale" },
    "height": { label: "Height", location: "In App / Relazionale" },
    "hourlyRate": { label: "Hourly Rate", location: "In App / Relazionale" },
    "iban": { label: "IBAN", location: "TabAnagrafica > Accordion Dati Bancari" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "insertionDate": { label: "Insertion Date", location: "In App / Relazionale" },
    "internalId": { label: "Internal  ID", location: "In App / Relazionale" },
    "isMinor": { label: "È Minorenne?", location: "Logica Backend (Calcolata)" },
    "lastName": { label: "Cognome", location: "TabAnagrafica > Dati Personali" },
    "lezioniPrivateAutorizzate": { label: "Lezioni Private Autorizzate", location: "In App / Relazionale" },
    "lezioniPrivateAutorizzateAt": { label: "Lezioni Private Autorizzate At", location: "In App / Relazionale" },
    "lezioniPrivateAutorizzateBy": { label: "Lezioni Private Autorizzate By", location: "In App / Relazionale" },
    "lezioniPrivateNote": { label: "Lezioni Private Note", location: "In App / Relazionale" },
    "mastroC": { label: "Mastro C", location: "In App / Relazionale" },
    "mastroCol": { label: "Mastro Col", location: "In App / Relazionale" },
    "medicalCertificateExpiry": { label: "Medical Certificate Expiry", location: "In App / Relazionale" },
    "membershipApplicationSigned": { label: "Membership Application Signed", location: "In App / Relazionale" },
    "mobile": { label: "Cellulare", location: "TabAnagrafica > Contatti" },
    "motherBirthDate": { label: "Mother Birth Date", location: "In App / Relazionale" },
    "motherBirthPlace": { label: "Mother Birth Place", location: "In App / Relazionale" },
    "motherBirthProvince": { label: "Mother Birth Province", location: "In App / Relazionale" },
    "motherCity": { label: "Mother City", location: "In App / Relazionale" },
    "motherEmail": { label: "Mother Email", location: "In App / Relazionale" },
    "motherFirstName": { label: "Mother First Name", location: "In App / Relazionale" },
    "motherFiscalCode": { label: "Mother Fiscal Code", location: "In App / Relazionale" },
    "motherLastName": { label: "Mother Last Name", location: "In App / Relazionale" },
    "motherMobile": { label: "Mother Mobile", location: "In App / Relazionale" },
    "motherPhone": { label: "Mother Phone", location: "In App / Relazionale" },
    "motherPostalCode": { label: "Mother Postal Code", location: "In App / Relazionale" },
    "motherProvince": { label: "Mother Province", location: "In App / Relazionale" },
    "motherStreetAddress": { label: "Mother Street Address", location: "In App / Relazionale" },
    "nationality": { label: "Nationality", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "pIva": { label: "Partita IVA", location: "TabAnagrafica > Accordion Fatturazione" },
    "participantType": { label: "Participant Type", location: "In App / Relazionale" },
    "patenteRilasciataDa": { label: "Patente Rilasciata Da", location: "In App / Relazionale" },
    "patenteScadenza": { label: "Patente Scadenza", location: "In App / Relazionale" },
    "patenteTipo": { label: "Patente Tipo", location: "In App / Relazionale" },
    "phone": { label: "Telefono Fisso", location: "TabAnagrafica > Contatti" },
    "photoUrl": { label: "Photo Url", location: "In App / Relazionale" },
    "placeOfBirth": { label: "Luogo di Nascita", location: "TabAnagrafica > Dati Personali" },
    "postalCode": { label: "CAP", location: "TabAnagrafica > Residenza" },
    "previousMembershipNumber": { label: "Previous Membership Number", location: "In App / Relazionale" },
    "privacyAccepted": { label: "Privacy Accepted", location: "In App / Relazionale" },
    "privacyDate": { label: "Privacy Date", location: "In App / Relazionale" },
    "profession": { label: "Profession", location: "In App / Relazionale" },
    "province": { label: "Provincia", location: "TabAnagrafica > Residenza" },
    "region": { label: "Region", location: "In App / Relazionale" },
    "regulationsAccepted": { label: "Regulations Accepted", location: "In App / Relazionale" },
    "residencePermit": { label: "Residence Permit", location: "In App / Relazionale" },
    "residencePermitExpiry": { label: "Residence Permit Expiry", location: "In App / Relazionale" },
    "schoolCreditsRequested": { label: "School Credits Requested", location: "In App / Relazionale" },
    "schoolCreditsYear": { label: "School Credits Year", location: "In App / Relazionale" },
    "season": { label: "Season", location: "In App / Relazionale" },
    "secondaryEmail": { label: "Secondary Email", location: "In App / Relazionale" },
    "sedeRiferimento": { label: "Sede Riferimento", location: "In App / Relazionale" },
    "sizePants": { label: "Size Pants", location: "In App / Relazionale" },
    "sizeShirt": { label: "Taglia Maglia", location: "TabAnagrafica > Accordion Merchandising" },
    "sizeShoes": { label: "Size Shoes", location: "In App / Relazionale" },
    "socialFacebook": { label: "Social Facebook", location: "In App / Relazionale" },
    "socialInstagram": { label: "Instagram", location: "TabAnagrafica > Accordion Social" },
    "socialTiktok": { label: "Social Tiktok", location: "In App / Relazionale" },
    "socialYoutube": { label: "Social Youtube", location: "In App / Relazionale" },
    "specialization": { label: "Specialization", location: "In App / Relazionale" },
    "staffStatus": { label: "Staff Status", location: "In App / Relazionale" },
    "subscriptionTypeId": { label: "Subscription Type  ID", location: "In App / Relazionale" },
    "tags": { label: "Tags", location: "In App / Relazionale" },
    "teamSegreteria": { label: "Team Segreteria", location: "In App / Relazionale" },
    "tessereMetadata": { label: "Tessere Metadata", location: "In App / Relazionale" },
    "tesserinoTecnicoIssueDate": { label: "Tesserino Tecnico Issue Date", location: "In App / Relazionale" },
    "tesserinoTecnicoNumber": { label: "Tesserino Tecnico Number", location: "In App / Relazionale" },
    "title": { label: "Title", location: "In App / Relazionale" },
    "tutor1BirthDate": { label: "Tutor1 Birth Date", location: "In App / Relazionale" },
    "tutor1BirthPlace": { label: "Tutor1 Birth Place", location: "In App / Relazionale" },
    "tutor1Email": { label: "Tutor1 Email", location: "In App / Relazionale" },
    "tutor1FiscalCode": { label: "Codice Fiscale Gen.1", location: "TabAnagrafica > Accordion Tutori" },
    "tutor1Phone": { label: "Telefono Gen.1", location: "TabAnagrafica > Accordion Tutori" },
    "tutor2BirthDate": { label: "Tutor2 Birth Date", location: "In App / Relazionale" },
    "tutor2BirthPlace": { label: "Tutor2 Birth Place", location: "In App / Relazionale" },
    "tutor2Email": { label: "Tutor2 Email", location: "In App / Relazionale" },
    "tutor2FirstName": { label: "Tutor2 First Name", location: "In App / Relazionale" },
    "tutor2FiscalCode": { label: "Codice Fiscale Gen.2", location: "TabAnagrafica > Accordion Tutori" },
    "tutor2LastName": { label: "Tutor2 Last Name", location: "In App / Relazionale" },
    "tutor2Phone": { label: "Tutor2 Phone", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
    "updatedBy": { label: "Updated By", location: "In App / Relazionale" },
    "userId": { label: "ID Autore (Relazione)", location: "Collegamento Operatore" },
    "website": { label: "Website", location: "In App / Relazionale" },
    "weight": { label: "Weight", location: "In App / Relazionale" },
    "whatsapp": { label: "Whatsapp", location: "In App / Relazionale" },
  },
  "payments": {
    "accountingCode": { label: "Codice Contabile", location: "Scheda Contabile" },
    "amount": { label: "Importo Pagato", location: "TabPagamenti > Modale Nuovo Pagamento" },
    "annualBalance": { label: "Saldo Annuale", location: "TabPagamenti > Ricalcolo Backend" },
    "bookingId": { label: "Booking  ID", location: "In App / Relazionale" },
    "costCenterCode": { label: "Cost Center Code", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "createdById": { label: "Created By  ID", location: "In App / Relazionale" },
    "deposit": { label: "Acconto", location: "TabPagamenti > Gestione Rate" },
    "description": { label: "Descrizione", location: "TabPagamenti > Riga Dettaglio" },
    "discountCode": { label: "Codice Sconto", location: "TabPagamenti > Sezione Sconti" },
    "discountPercentage": { label: "Discount Percentage", location: "In App / Relazionale" },
    "discountValue": { label: "Discount Value", location: "In App / Relazionale" },
    "dueDate": { label: "Data Scadenza", location: "TabPagamenti > Gestione Rate" },
    "enrollmentDetailLabels": { label: "Enrollment Detail Labels", location: "In App / Relazionale" },
    "enrollmentId": { label: "Enrollment  ID", location: "In App / Relazionale" },
    "gbrhDataEmissione": { label: "Gbrh Data Emissione", location: "In App / Relazionale" },
    "gbrhDataScadenza": { label: "Gbrh Data Scadenza", location: "In App / Relazionale" },
    "gbrhDataUtilizzo": { label: "Gbrh Data Utilizzo", location: "In App / Relazionale" },
    "gbrhIban": { label: "IBAN (Bonifici)", location: "TabPagamenti > Campi Dinamici Bonifico" },
    "gbrhNumero": { label: "Gbrh Numero", location: "In App / Relazionale" },
    "globalEnrollmentId": { label: "Global Enrollment  ID", location: "In App / Relazionale" },
    "id": { label: "ID Pagamento", location: "Sistema Centrale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "membershipId": { label: "Membership  ID", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "operatorName": { label: "Operator Name", location: "In App / Relazionale" },
    "paidDate": { label: "Data Pagamento", location: "TabPagamenti > Ricevuta" },
    "paymentMethod": { label: "Metodo (Contanti/POS...)", location: "TabPagamenti > Modale Nuovo Pagamento" },
    "paymentMethodId": { label: "Payment Method  ID", location: "In App / Relazionale" },
    "paymentNoteLabels": { label: "Payment Note Labels", location: "In App / Relazionale" },
    "period": { label: "Period", location: "In App / Relazionale" },
    "promoCode": { label: "Promo Code", location: "In App / Relazionale" },
    "promoPercentage": { label: "Promo Percentage", location: "In App / Relazionale" },
    "promoValue": { label: "Promo Value", location: "In App / Relazionale" },
    "quantity": { label: "Quantity", location: "In App / Relazionale" },
    "quotaDescription": { label: "Quota Description", location: "In App / Relazionale" },
    "receiptsCount": { label: "Receipts Count", location: "In App / Relazionale" },
    "seasonId": { label: "Season  ID", location: "In App / Relazionale" },
    "source": { label: "Source", location: "In App / Relazionale" },
    "status": { label: "Stato (Saldato/Rata)", location: "TabPagamenti > Badge Stato" },
    "totalQuota": { label: "Total Quota", location: "In App / Relazionale" },
    "transferConfirmationDate": { label: "Transfer Confirmation Date", location: "In App / Relazionale" },
    "type": { label: "Tipo Transazione", location: "TabPagamenti > Griglia" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
    "updatedById": { label: "Updated By  ID", location: "In App / Relazionale" },
    "vatCode": { label: "Vat Code", location: "In App / Relazionale" },
  },
  "courses": {
    "active": { label: "Attivo?", location: "Flag Visibilità" },
    "activeOnHolidays": { label: "Active On Holidays", location: "In App / Relazionale" },
    "activityType": { label: "Tipo Attività (es. Corso)", location: "Filtri Ricerca" },
    "ageGroup": { label: "Age Group", location: "In App / Relazionale" },
    "categoryId": { label: "Category  ID", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "currentEnrollment": { label: "Current Enrollment", location: "In App / Relazionale" },
    "dayOfWeek": { label: "Day Of Week", location: "In App / Relazionale" },
    "description": { label: "Descrizione", location: "Campo Testuale" },
    "endDate": { label: "End Date", location: "In App / Relazionale" },
    "endTime": { label: "End Time", location: "In App / Relazionale" },
    "googleEventId": { label: "Google Event  ID", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "instructorId": { label: "Insegnante", location: "Scheda Corso > Assegnazione" },
    "internalTags": { label: "Internal Tags", location: "In App / Relazionale" },
    "lessonType": { label: "Lesson Type", location: "In App / Relazionale" },
    "level": { label: "Level", location: "In App / Relazionale" },
    "maxCapacity": { label: "Capacità Massima", location: "Scheda Corso > Regole" },
    "name": { label: "Nome Corso", location: "Intestazione Scheda Corso" },
    "numberOfPeople": { label: "Number Of People", location: "In App / Relazionale" },
    "price": { label: "Prezzo Base", location: "Scheda Corso > Listino" },
    "quoteId": { label: "Quote  ID", location: "In App / Relazionale" },
    "recurrenceType": { label: "Recurrence Type", location: "In App / Relazionale" },
    "schedule": { label: "Orario", location: "Scheda Corso > Planning" },
    "seasonId": { label: "Season  ID", location: "In App / Relazionale" },
    "secondaryInstructor1Id": { label: "Secondary Instructor1  ID", location: "In App / Relazionale" },
    "sku": { label: "Codice Univoco (SKU)", location: "Impostazioni Corso" },
    "startDate": { label: "Start Date", location: "In App / Relazionale" },
    "startTime": { label: "Start Time", location: "In App / Relazionale" },
    "statusTags": { label: "Status Tags", location: "In App / Relazionale" },
    "studioId": { label: "Studio  ID", location: "In App / Relazionale" },
    "totalOccurrences": { label: "Total Occurrences", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "memberships": {
    "barcode": { label: "Barcode", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "dataQualityFlag": { label: "Data Quality Flag", location: "In App / Relazionale" },
    "entityCardExpiryDate": { label: "Entity Card Expiry Date", location: "In App / Relazionale" },
    "entityCardNumber": { label: "Entity Card Number", location: "In App / Relazionale" },
    "expiryDate": { label: "Data Scadenza", location: "TabTessere > Form" },
    "fee": { label: "Quota Versata", location: "Integrazione Pagamenti" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isRenewal": { label: "È Rinnovo?", location: "Logica Automatica Backend" },
    "issueDate": { label: "Data Emissione", location: "TabTessere > Form" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "membershipNumber": { label: "Numero Tessera", location: "TabTessere > Dettaglio" },
    "membershipType": { label: "Membership Type", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "previousMembershipNumber": { label: "Previous Membership Number", location: "In App / Relazionale" },
    "renewalType": { label: "Renewal Type", location: "In App / Relazionale" },
    "renewedFromId": { label: "Renewed From  ID", location: "In App / Relazionale" },
    "seasonCompetence": { label: "Season Competence", location: "In App / Relazionale" },
    "seasonEndYear": { label: "Season End Year", location: "In App / Relazionale" },
    "seasonId": { label: "Season  ID", location: "In App / Relazionale" },
    "seasonStartYear": { label: "Season Start Year", location: "In App / Relazionale" },
    "status": { label: "Stato (Attiva/Scaduta)", location: "TabTessere > Badge" },
    "type": { label: "Type", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "companyAgreements": {
    "approvedBy": { label: "Approved By", location: "In App / Relazionale" },
    "companyName": { label: "Company Name", location: "In App / Relazionale" },
    "companyType": { label: "Company Type", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "discountCourses": { label: "Discount Courses", location: "In App / Relazionale" },
    "discountMerch": { label: "Discount Merch", location: "In App / Relazionale" },
    "discountOther": { label: "Discount Other", location: "In App / Relazionale" },
    "eligibleWho": { label: "Eligible Who", location: "In App / Relazionale" },
    "excludeOpen": { label: "Exclude Open", location: "In App / Relazionale" },
    "excludeOtherPromos": { label: "Exclude Other Promos", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isActive": { label: "Is Active", location: "In App / Relazionale" },
    "metadata": { label: "Metadata", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "promoRuleId": { label: "Promo Rule  ID", location: "In App / Relazionale" },
    "requiresVerification": { label: "Requires Verification", location: "In App / Relazionale" },
    "specialRules": { label: "Special Rules", location: "In App / Relazionale" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
    "validFrom": { label: "Valid From", location: "In App / Relazionale" },
    "validTo": { label: "Valid To", location: "In App / Relazionale" },
    "verificationNotes": { label: "Verification Notes", location: "In App / Relazionale" },
  },
  "memberDiscounts": {
    "approvedAt": { label: "Approved At", location: "In App / Relazionale" },
    "approvedBy": { label: "Approved By", location: "In App / Relazionale" },
    "bonusNote": { label: "Bonus Note", location: "In App / Relazionale" },
    "companyAgreementId": { label: "Company Agreement  ID", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "createdById": { label: "Created By  ID", location: "In App / Relazionale" },
    "discountPercent": { label: "Discount Percent", location: "In App / Relazionale" },
    "discountType": { label: "Discount Type", location: "In App / Relazionale" },
    "discountValue": { label: "Discount Value", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "internalNotes": { label: "Internal Notes", location: "In App / Relazionale" },
    "isUsed": { label: "Is Used", location: "In App / Relazionale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "metadata": { label: "Metadata", location: "In App / Relazionale" },
    "paymentId": { label: "Payment  ID", location: "In App / Relazionale" },
    "promoRuleId": { label: "Promo Rule  ID", location: "In App / Relazionale" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
    "usedAt": { label: "Used At", location: "In App / Relazionale" },
    "validForSeasonId": { label: "Valid For Season  ID", location: "In App / Relazionale" },
    "validFrom": { label: "Valid From", location: "In App / Relazionale" },
    "validTo": { label: "Valid To", location: "In App / Relazionale" },
  },
  "teamMonthlyReports": {
    "anno": { label: "Anno", location: "In App / Relazionale" },
    "cntAG": { label: "Cnt A G", location: "In App / Relazionale" },
    "cntAI": { label: "Cnt A I", location: "In App / Relazionale" },
    "cntF": { label: "Cnt F", location: "In App / Relazionale" },
    "cntFE": { label: "Cnt F E", location: "In App / Relazionale" },
    "cntIN": { label: "Cnt I N", location: "In App / Relazionale" },
    "cntML": { label: "Cnt M L", location: "In App / Relazionale" },
    "cntMT": { label: "Cnt M T", location: "In App / Relazionale" },
    "cntPE": { label: "Cnt P E", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "employeeId": { label: "ID Dipendente (Relazione)", location: "Gestione Team" },
    "exportAt": { label: "Export At", location: "In App / Relazionale" },
    "giorniLavorati": { label: "Giorni Lavorati", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "importoExtra": { label: "Importo Extra", location: "In App / Relazionale" },
    "locked": { label: "Locked", location: "In App / Relazionale" },
    "mese": { label: "Mese", location: "In App / Relazionale" },
    "oreExtraNeg": { label: "Ore Extra Neg", location: "In App / Relazionale" },
    "oreExtraPos": { label: "Ore Extra Pos", location: "In App / Relazionale" },
    "oreTotali": { label: "Ore Totali", location: "In App / Relazionale" },
    "stipendioFisso": { label: "Stipendio Fisso", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "promoRules": {
    "approvedBy": { label: "Approved By", location: "In App / Relazionale" },
    "code": { label: "Code", location: "In App / Relazionale" },
    "companyName": { label: "Company Name", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "excludeOpen": { label: "Exclude Open", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "internalNotes": { label: "Internal Notes", location: "In App / Relazionale" },
    "label": { label: "Label", location: "In App / Relazionale" },
    "maxUses": { label: "Max Uses", location: "In App / Relazionale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "metadata": { label: "Metadata", location: "In App / Relazionale" },
    "notCumulative": { label: "Not Cumulative", location: "In App / Relazionale" },
    "ruleType": { label: "Rule Type", location: "In App / Relazionale" },
    "targetType": { label: "Target Type", location: "In App / Relazionale" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
    "usedCount": { label: "Used Count", location: "In App / Relazionale" },
    "validFrom": { label: "Valid From", location: "In App / Relazionale" },
    "validTo": { label: "Valid To", location: "In App / Relazionale" },
    "value": { label: "Value", location: "In App / Relazionale" },
  },
  "carnetWallets": {
    "bonusUnits": { label: "Bonus Units", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "expiresAt": { label: "Expires At", location: "In App / Relazionale" },
    "expiryDays": { label: "Expiry Days", location: "In App / Relazionale" },
    "groupSize": { label: "Group Size", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isActive": { label: "Is Active", location: "In App / Relazionale" },
    "locationType": { label: "Location Type", location: "In App / Relazionale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "paymentId": { label: "Payment  ID", location: "In App / Relazionale" },
    "pricePerUnit": { label: "Price Per Unit", location: "In App / Relazionale" },
    "purchasedAt": { label: "Purchased At", location: "In App / Relazionale" },
    "totalPaid": { label: "Total Paid", location: "In App / Relazionale" },
    "totalUnits": { label: "Total Units", location: "In App / Relazionale" },
    "trialDate": { label: "Trial Date", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
    "usedUnits": { label: "Used Units", location: "In App / Relazionale" },
    "walletTypeId": { label: "Wallet Type  ID", location: "In App / Relazionale" },
  },
  "pricingRules": {
    "appliesTo": { label: "Applies To", location: "In App / Relazionale" },
    "authorizedBy": { label: "Authorized By", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "effectType": { label: "Effect Type", location: "In App / Relazionale" },
    "effectValue": { label: "Effect Value", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isActive": { label: "Is Active", location: "In App / Relazionale" },
    "metadata": { label: "Metadata", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "priority": { label: "Priority", location: "In App / Relazionale" },
    "requiresAuthorization": { label: "Requires Authorization", location: "In App / Relazionale" },
    "ruleCode": { label: "Rule Code", location: "In App / Relazionale" },
    "ruleLabel": { label: "Rule Label", location: "In App / Relazionale" },
    "ruleType": { label: "Rule Type", location: "In App / Relazionale" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
    "triggerCondition": { label: "Trigger Condition", location: "In App / Relazionale" },
    "triggerValue": { label: "Trigger Value", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "instructorAgreements": {
    "agreementType": { label: "Agreement Type", location: "In App / Relazionale" },
    "baseMonthlyAmount": { label: "Base Monthly Amount", location: "In App / Relazionale" },
    "billingDay": { label: "Billing Day", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isActive": { label: "Is Active", location: "In App / Relazionale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "metadata": { label: "Metadata", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "packHours": { label: "Pack Hours", location: "In App / Relazionale" },
    "paymentMode": { label: "Payment Mode", location: "In App / Relazionale" },
    "scheduleNotes": { label: "Schedule Notes", location: "In App / Relazionale" },
    "seasonId": { label: "Season  ID", location: "In App / Relazionale" },
    "speseMensili": { label: "Spese Mensili", location: "In App / Relazionale" },
    "studioId": { label: "Studio  ID", location: "In App / Relazionale" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "strategicEvents": {
    "affectsCalendar": { label: "Affects Calendar", location: "In App / Relazionale" },
    "affectsPayments": { label: "Affects Payments", location: "In App / Relazionale" },
    "affectsPlanning": { label: "Affects Planning", location: "In App / Relazionale" },
    "allDay": { label: "All Day", location: "In App / Relazionale" },
    "color": { label: "Colore UI", location: "Personalizzazione Grafica" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "description": { label: "Descrizione", location: "Campo Testuale" },
    "endDate": { label: "End Date", location: "In App / Relazionale" },
    "eventType": { label: "Event Type", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isPublicHoliday": { label: "Is Public Holiday", location: "In App / Relazionale" },
    "seasonId": { label: "Season  ID", location: "In App / Relazionale" },
    "startDate": { label: "Start Date", location: "In App / Relazionale" },
    "status": { label: "Stato", location: "Gestione Stato" },
    "studioId": { label: "Studio  ID", location: "In App / Relazionale" },
    "title": { label: "Title", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "studioBookings": {
    "amount": { label: "Importo", location: "Logica Finanziaria" },
    "bookingDate": { label: "Booking Date", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "description": { label: "Descrizione", location: "Campo Testuale" },
    "endTime": { label: "End Time", location: "In App / Relazionale" },
    "googleEventId": { label: "Google Event  ID", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "instructorId": { label: "ID Insegnante (Relazione)", location: "Assegnazione Corsi" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "paid": { label: "Paid", location: "In App / Relazionale" },
    "seasonId": { label: "Season  ID", location: "In App / Relazionale" },
    "serviceId": { label: "Service  ID", location: "In App / Relazionale" },
    "startTime": { label: "Start Time", location: "In App / Relazionale" },
    "status": { label: "Stato", location: "Gestione Stato" },
    "studioId": { label: "Studio  ID", location: "In App / Relazionale" },
    "title": { label: "Title", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "users": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "currentSessionStart": { label: "Current Session Start", location: "In App / Relazionale" },
    "email": { label: "Email", location: "In App / Relazionale" },
    "emailVerified": { label: "Email Verified", location: "In App / Relazionale" },
    "firstName": { label: "First Name", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "lastName": { label: "Last Name", location: "In App / Relazionale" },
    "lastSeenAt": { label: "Last Seen At", location: "In App / Relazionale" },
    "lastSessionDuration": { label: "Last Session Duration", location: "In App / Relazionale" },
    "otpExpiresAt": { label: "Otp Expires At", location: "In App / Relazionale" },
    "otpToken": { label: "Otp Token", location: "In App / Relazionale" },
    "password": { label: "Password", location: "In App / Relazionale" },
    "phone": { label: "Phone", location: "In App / Relazionale" },
    "profileImageUrl": { label: "Profile Image Url", location: "In App / Relazionale" },
    "role": { label: "Role", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
    "username": { label: "Username", location: "In App / Relazionale" },
  },
  "enrollments": {
    "completionNotes": { label: "Completion Notes", location: "In App / Relazionale" },
    "courseId": { label: "ID Corso (Relazione)", location: "Collegamento Attività" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "details": { label: "Details", location: "In App / Relazionale" },
    "enrollmentDate": { label: "Enrollment Date", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "onlineSource": { label: "Online Source", location: "In App / Relazionale" },
    "participationType": { label: "Tipo Iscrizione (Annuale/Quad)", location: "TabIscrizioni > Dettaglio" },
    "pendingMedicalCert": { label: "In Attesa Certificato", location: "Alert Sistema" },
    "pendingMembership": { label: "Pending Membership", location: "In App / Relazionale" },
    "seasonId": { label: "Season  ID", location: "In App / Relazionale" },
    "sourceFile": { label: "Source File", location: "In App / Relazionale" },
    "status": { label: "Stato Frequenza", location: "TabIscrizioni > Badge" },
    "targetDate": { label: "Data Iscrizione", location: "TabIscrizioni > Storico" },
  },
  "journalEntries": {
    "amount": { label: "Importo", location: "Logica Finanziaria" },
    "costCenterId": { label: "Cost Center  ID", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "createdById": { label: "Created By  ID", location: "In App / Relazionale" },
    "creditAccount": { label: "Credit Account", location: "In App / Relazionale" },
    "debitAccount": { label: "Debit Account", location: "In App / Relazionale" },
    "description": { label: "Descrizione", location: "Campo Testuale" },
    "entryDate": { label: "Entry Date", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isAuto": { label: "Is Auto", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "paymentId": { label: "Payment  ID", location: "In App / Relazionale" },
    "periodId": { label: "Period  ID", location: "In App / Relazionale" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
    "vatAmount": { label: "Vat Amount", location: "In App / Relazionale" },
    "vatCode": { label: "Vat Code", location: "In App / Relazionale" },
  },
  "staffRates": {
    "amount": { label: "Importo", location: "Logica Finanziaria" },
    "applicableTo": { label: "Applicable To", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isActive": { label: "Is Active", location: "In App / Relazionale" },
    "maxSessionsPerWeek": { label: "Max Sessions Per Week", location: "In App / Relazionale" },
    "metadata": { label: "Metadata", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "rateType": { label: "Rate Type", location: "In App / Relazionale" },
    "requiresMedicalCert": { label: "Requires Medical Cert", location: "In App / Relazionale" },
    "requiresMembership": { label: "Requires Membership", location: "In App / Relazionale" },
    "serviceCode": { label: "Service Code", location: "In App / Relazionale" },
    "serviceLabel": { label: "Service Label", location: "In App / Relazionale" },
    "studioRestriction": { label: "Studio Restriction", location: "In App / Relazionale" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "activities": {
    "basePrice": { label: "Base Price", location: "In App / Relazionale" },
    "categoryId": { label: "Category  ID", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "endTime": { label: "End Time", location: "In App / Relazionale" },
    "extraInfoOverrides": { label: "Extra Info Overrides", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "instructorId": { label: "ID Insegnante (Relazione)", location: "Assegnazione Corsi" },
    "isPunchCard": { label: "Is Punch Card", location: "In App / Relazionale" },
    "locationId": { label: "Location  ID", location: "In App / Relazionale" },
    "maxCapacity": { label: "Max Capacity", location: "In App / Relazionale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "punchCardTotalAccesses": { label: "Punch Card Total Accesses", location: "In App / Relazionale" },
    "startTime": { label: "Start Time", location: "In App / Relazionale" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "priceMatrix": {
    "basePrice": { label: "Base Price", location: "In App / Relazionale" },
    "category": { label: "Category", location: "In App / Relazionale" },
    "courseCount": { label: "Course Count", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "excludeFromPromo": { label: "Exclude From Promo", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "maxSlots": { label: "Max Slots", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "quantityType": { label: "Quantity Type", location: "In App / Relazionale" },
    "seasonId": { label: "Season  ID", location: "In App / Relazionale" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
    "validFromMonth": { label: "Valid From Month", location: "In App / Relazionale" },
    "validToMonth": { label: "Valid To Month", location: "In App / Relazionale" },
  },
  "staffSostituzioni": {
    "absenceDate": { label: "Absence Date", location: "In App / Relazionale" },
    "absentMemberId": { label: "Absent Member  ID", location: "In App / Relazionale" },
    "amountOverride": { label: "Amount Override", location: "In App / Relazionale" },
    "courseId": { label: "ID Corso (Relazione)", location: "Collegamento Attività" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "createdBy": { label: "Created By", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "lessonDescription": { label: "Lesson Description", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "paymentTo": { label: "Payment To", location: "In App / Relazionale" },
    "substituteMemberId": { label: "Substitute Member  ID", location: "In App / Relazionale" },
    "vistoElisa": { label: "Visto Elisa", location: "In App / Relazionale" },
    "vistoSegreteria": { label: "Visto Segreteria", location: "In App / Relazionale" },
  },
  "teamLeaveRequests": {
    "approvedAt": { label: "Approved At", location: "In App / Relazionale" },
    "approvedBy": { label: "Approved By", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "dataFine": { label: "Data Fine", location: "In App / Relazionale" },
    "dataInizio": { label: "Data Inizio", location: "In App / Relazionale" },
    "employeeId": { label: "ID Dipendente (Relazione)", location: "Gestione Team" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "noteAdmin": { label: "Note Admin", location: "In App / Relazionale" },
    "noteDipendente": { label: "Note Dipendente", location: "In App / Relazionale" },
    "oreTotali": { label: "Ore Totali", location: "In App / Relazionale" },
    "status": { label: "Stato", location: "Gestione Stato" },
    "tipo": { label: "Tipo", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "teamShiftDiaryEntries": {
    "activityTypeId": { label: "Activity Type  ID", location: "In App / Relazionale" },
    "attivitaLibera": { label: "Attivita Libera", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "data": { label: "Data", location: "In App / Relazionale" },
    "employeeId": { label: "ID Dipendente (Relazione)", location: "Gestione Team" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "minuti": { label: "Minuti", location: "In App / Relazionale" },
    "note": { label: "Note", location: "In App / Relazionale" },
    "okFlag": { label: "Ok Flag", location: "In App / Relazionale" },
    "oraSlot": { label: "Ora Slot", location: "In App / Relazionale" },
    "postazione": { label: "Postazione", location: "In App / Relazionale" },
    "quantita": { label: "Quantita", location: "In App / Relazionale" },
    "shiftId": { label: "Shift  ID", location: "In App / Relazionale" },
  },
  "gemConversations": {
    "assignedTo": { label: "Assigned To", location: "In App / Relazionale" },
    "botContext": { label: "Bot Context", location: "In App / Relazionale" },
    "channel": { label: "Channel", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "lastMessageAt": { label: "Last Message At", location: "In App / Relazionale" },
    "participantId": { label: "Participant  ID", location: "In App / Relazionale" },
    "participantUserId": { label: "Participant User  ID", location: "In App / Relazionale" },
    "status": { label: "Stato", location: "Gestione Stato" },
    "unreadParticipant": { label: "Unread Participant", location: "In App / Relazionale" },
    "unreadTeam": { label: "Unread Team", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "gemMessages": {
    "attachmentName": { label: "Attachment Name", location: "In App / Relazionale" },
    "attachmentSize": { label: "Attachment Size", location: "In App / Relazionale" },
    "attachmentUrl": { label: "Attachment Url", location: "In App / Relazionale" },
    "content": { label: "Content", location: "In App / Relazionale" },
    "conversationId": { label: "Conversation  ID", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isRead": { label: "Is Read", location: "In App / Relazionale" },
    "quickLinkId": { label: "Quick Link  ID", location: "In App / Relazionale" },
    "quickLinkType": { label: "Quick Link Type", location: "In App / Relazionale" },
    "senderId": { label: "Sender  ID", location: "In App / Relazionale" },
    "senderType": { label: "Sender Type", location: "In App / Relazionale" },
  },
  "memberFormsSubmissions": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "createdBy": { label: "Created By", location: "In App / Relazionale" },
    "formType": { label: "Form Type", location: "In App / Relazionale" },
    "formVersion": { label: "Form Version", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "payloadData": { label: "Payload Data", location: "In App / Relazionale" },
    "seasonId": { label: "Season  ID", location: "In App / Relazionale" },
    "signatureHash": { label: "Signature Hash", location: "In App / Relazionale" },
    "signedAt": { label: "Signed At", location: "In App / Relazionale" },
    "signedByIp": { label: "Signed By Ip", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "memberUploads": {
    "documentType": { label: "Document Type", location: "In App / Relazionale" },
    "fileSize": { label: "File Size", location: "In App / Relazionale" },
    "fileUrl": { label: "File Url", location: "In App / Relazionale" },
    "filename": { label: "Filename", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "mimeType": { label: "Mime Type", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "seasonId": { label: "Season  ID", location: "In App / Relazionale" },
    "uploadedAt": { label: "Uploaded At", location: "In App / Relazionale" },
    "verifiedAt": { label: "Verified At", location: "In App / Relazionale" },
    "verifiedBy": { label: "Verified By", location: "In App / Relazionale" },
  },
  "payslips": {
    "confirmedAt": { label: "Confirmed At", location: "In App / Relazionale" },
    "confirmedBy": { label: "Confirmed By", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "hoursTaught": { label: "Hours Taught", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "month": { label: "Month", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "rate": { label: "Rate", location: "In App / Relazionale" },
    "status": { label: "Stato", location: "Gestione Stato" },
    "total": { label: "Total", location: "In App / Relazionale" },
    "year": { label: "Year", location: "In App / Relazionale" },
  },
  "studios": {
    "active": { label: "Attivo?", location: "Flag Visibilità" },
    "capacity": { label: "Capacity", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "equipment": { label: "Equipment", location: "In App / Relazionale" },
    "floor": { label: "Floor", location: "In App / Relazionale" },
    "googleCalendarId": { label: "Google Calendar  ID", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "operatingDays": { label: "Operating Days", location: "In App / Relazionale" },
    "operatingHours": { label: "Operating Hours", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "teamEmployees": {
    "attivo": { label: "Attivo", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "dataAssunzione": { label: "Data Assunzione", location: "In App / Relazionale" },
    "displayOrder": { label: "Display Order", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "noteHr": { label: "Note Hr", location: "In App / Relazionale" },
    "stipendioFissoMensile": { label: "Stipendio Fisso Mensile", location: "In App / Relazionale" },
    "tariffaOraria": { label: "Tariffa Oraria", location: "In App / Relazionale" },
    "team": { label: "Team", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
    "userId": { label: "ID Autore (Relazione)", location: "Collegamento Operatore" },
  },
  "teamNotes": {
    "authorId": { label: "Author  ID", location: "In App / Relazionale" },
    "authorName": { label: "Author Name", location: "In App / Relazionale" },
    "category": { label: "Category", location: "In App / Relazionale" },
    "content": { label: "Content", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "deletedAt": { label: "Data Eliminazione", location: "Cestino / Audit" },
    "deletedBy": { label: "Eliminato Da", location: "Cestino / Audit" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isPinned": { label: "Is Pinned", location: "In App / Relazionale" },
    "targetUrl": { label: "Target Url", location: "In App / Relazionale" },
    "title": { label: "Title", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "customReports": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "createdBy": { label: "Created By", location: "In App / Relazionale" },
    "description": { label: "Descrizione", location: "Campo Testuale" },
    "entityType": { label: "Entity Type", location: "In App / Relazionale" },
    "filters": { label: "Filters", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "selectedFields": { label: "Selected Fields", location: "In App / Relazionale" },
    "sortDirection": { label: "Sort Direction", location: "In App / Relazionale" },
    "sortField": { label: "Sort Field", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "memberPackages": {
    "active": { label: "Attivo?", location: "Flag Visibilità" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "packageCode": { label: "Package Code", location: "In App / Relazionale" },
    "packageType": { label: "Package Type", location: "In App / Relazionale" },
    "pricePaid": { label: "Price Paid", location: "In App / Relazionale" },
    "totalUses": { label: "Total Uses", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
    "usedUses": { label: "Used Uses", location: "In App / Relazionale" },
  },
  "staffDisciplinaryLog": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "createdBy": { label: "Created By", location: "In App / Relazionale" },
    "decision": { label: "Decision", location: "In App / Relazionale" },
    "description": { label: "Descrizione", location: "Campo Testuale" },
    "eventDate": { label: "Event Date", location: "In App / Relazionale" },
    "eventType": { label: "Event Type", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "resolvedAt": { label: "Resolved At", location: "In App / Relazionale" },
    "staffResponse": { label: "Staff Response", location: "In App / Relazionale" },
    "staffResponseAt": { label: "Staff Response At", location: "In App / Relazionale" },
  },
  "staffPresenze": {
    "confirmedAt": { label: "Confirmed At", location: "In App / Relazionale" },
    "confirmedBy": { label: "Confirmed By", location: "In App / Relazionale" },
    "courseId": { label: "ID Corso (Relazione)", location: "Collegamento Attività" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "date": { label: "Date", location: "In App / Relazionale" },
    "hours": { label: "Hours", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "source": { label: "Source", location: "In App / Relazionale" },
    "status": { label: "Stato", location: "Gestione Stato" },
  },
  "teamAttendanceLogs": {
    "checkIn": { label: "Check In", location: "In App / Relazionale" },
    "checkOut": { label: "Check Out", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "data": { label: "Data", location: "In App / Relazionale" },
    "employeeId": { label: "ID Dipendente (Relazione)", location: "Gestione Team" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "modifiedAt": { label: "Modified At", location: "In App / Relazionale" },
    "modifiedByAdmin": { label: "Modified By Admin", location: "In App / Relazionale" },
    "note": { label: "Note", location: "In App / Relazionale" },
    "oreLavorate": { label: "Ore Lavorate", location: "In App / Relazionale" },
    "tipoAssenza": { label: "Tipo Assenza", location: "In App / Relazionale" },
  },
  "teamDocumentVersions": {
    "documentId": { label: "Document  ID", location: "In App / Relazionale" },
    "fileName": { label: "File Name", location: "In App / Relazionale" },
    "fileSize": { label: "File Size", location: "In App / Relazionale" },
    "fileUrl": { label: "File Url", location: "In App / Relazionale" },
    "hashFile": { label: "Hash File", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "mimeType": { label: "Mime Type", location: "In App / Relazionale" },
    "noteVersione": { label: "Note Versione", location: "In App / Relazionale" },
    "uploadedAt": { label: "Uploaded At", location: "In App / Relazionale" },
    "uploadedBy": { label: "Uploaded By", location: "In App / Relazionale" },
    "versioneNumero": { label: "Versione Numero", location: "In App / Relazionale" },
  },
  "teamScheduledShifts": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "createdByUserId": { label: "Created By User  ID", location: "In App / Relazionale" },
    "data": { label: "Data", location: "In App / Relazionale" },
    "employeeId": { label: "ID Dipendente (Relazione)", location: "Gestione Team" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "modifiedByUserId": { label: "Modified By User  ID", location: "In App / Relazionale" },
    "note": { label: "Note", location: "In App / Relazionale" },
    "oraFine": { label: "Ora Fine", location: "In App / Relazionale" },
    "oraInizio": { label: "Ora Inizio", location: "In App / Relazionale" },
    "postazione": { label: "Postazione", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "webhookLogs": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "errorMessage": { label: "Error Message", location: "In App / Relazionale" },
    "eventType": { label: "Event Type", location: "In App / Relazionale" },
    "externalId": { label: "External  ID", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "paymentId": { label: "Payment  ID", location: "In App / Relazionale" },
    "processedAt": { label: "Processed At", location: "In App / Relazionale" },
    "rawPayload": { label: "Raw Payload", location: "In App / Relazionale" },
    "source": { label: "Source", location: "In App / Relazionale" },
    "status": { label: "Stato", location: "Gestione Stato" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
  },
  "welfareProviders": {
    "availableCategories": { label: "Available Categories", location: "In App / Relazionale" },
    "extraFeePercent": { label: "Extra Fee Percent", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isActive": { label: "Is Active", location: "In App / Relazionale" },
    "metadata": { label: "Metadata", location: "In App / Relazionale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "operativeNotes": { label: "Operative Notes", location: "In App / Relazionale" },
    "requiresMedicalCert": { label: "Requires Medical Cert", location: "In App / Relazionale" },
    "requiresMembershipFee": { label: "Requires Membership Fee", location: "In App / Relazionale" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "accountingPeriods": {
    "closedAt": { label: "Closed At", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isClosed": { label: "Is Closed", location: "In App / Relazionale" },
    "label": { label: "Label", location: "In App / Relazionale" },
    "month": { label: "Month", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "seasonId": { label: "Season  ID", location: "In App / Relazionale" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
    "year": { label: "Year", location: "In App / Relazionale" },
  },
  "attendances": {
    "attendanceDate": { label: "Attendance Date", location: "In App / Relazionale" },
    "courseId": { label: "ID Corso (Relazione)", location: "Collegamento Attività" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "enrollmentId": { label: "Enrollment  ID", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "seasonId": { label: "Season  ID", location: "In App / Relazionale" },
    "type": { label: "Type", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "carnetSessions": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "instructorId": { label: "ID Insegnante (Relazione)", location: "Assegnazione Corsi" },
    "isBonus": { label: "Is Bonus", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "sessionDate": { label: "Session Date", location: "In App / Relazionale" },
    "sessionNumber": { label: "Session Number", location: "In App / Relazionale" },
    "sessionTimeEnd": { label: "Session Time End", location: "In App / Relazionale" },
    "sessionTimeStart": { label: "Session Time Start", location: "In App / Relazionale" },
    "walletId": { label: "Wallet  ID", location: "In App / Relazionale" },
  },
  "courseQuotesGrid": {
    "activityType": { label: "Activity Type", location: "In App / Relazionale" },
    "category": { label: "Category", location: "In App / Relazionale" },
    "corsiWeek": { label: "Corsi Week", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "description": { label: "Descrizione", location: "Campo Testuale" },
    "details": { label: "Details", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "monthsData": { label: "Months Data", location: "In App / Relazionale" },
    "sortOrder": { label: "Ordine (Ordinamento)", location: "Visualizzazione Elenchi" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "globalEnrollments": {
    "activityId": { label: "Activity  ID", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "extraInfoData": { label: "Extra Info Data", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "remainingPunchCards": { label: "Remaining Punch Cards", location: "In App / Relazionale" },
    "status": { label: "Stato", location: "Gestione Stato" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
    "walletCredit": { label: "Wallet Credit", location: "In App / Relazionale" },
  },
  "teamComments": {
    "assignedTo": { label: "Assigned To", location: "In App / Relazionale" },
    "authorId": { label: "Author  ID", location: "In App / Relazionale" },
    "authorName": { label: "Author Name", location: "In App / Relazionale" },
    "content": { label: "Content", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isResolved": { label: "Is Resolved", location: "In App / Relazionale" },
    "parentId": { label: "Parent  ID", location: "In App / Relazionale" },
    "priority": { label: "Priority", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "teamEmployeeActivityLog": {
    "azione": { label: "Azione", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "employeeId": { label: "ID Dipendente (Relazione)", location: "Gestione Team" },
    "entitaId": { label: "Entita  ID", location: "In App / Relazionale" },
    "entitaModificata": { label: "Entita Modificata", location: "In App / Relazionale" },
    "eseguitaDa": { label: "Eseguita Da", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "ipAddress": { label: "Ip Address", location: "In App / Relazionale" },
    "valoreDopo": { label: "Valore Dopo", location: "In App / Relazionale" },
    "valorePrima": { label: "Valore Prima", location: "In App / Relazionale" },
  },
  "aiUsageLogs": {
    "action": { label: "Action", location: "In App / Relazionale" },
    "completionTokens": { label: "Completion Tokens", location: "In App / Relazionale" },
    "costUsd": { label: "Cost Usd", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "model": { label: "Model", location: "In App / Relazionale" },
    "promptTokens": { label: "Prompt Tokens", location: "In App / Relazionale" },
    "totalTokens": { label: "Total Tokens", location: "In App / Relazionale" },
    "userId": { label: "ID Autore (Relazione)", location: "Collegamento Operatore" },
  },
  "medicalCertificates": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "doctorName": { label: "Doctor Name", location: "In App / Relazionale" },
    "expiryDate": { label: "Expiry Date", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "issueDate": { label: "Issue Date", location: "In App / Relazionale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "status": { label: "Stato", location: "Gestione Stato" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "pagodilTiers": {
    "feeAmount": { label: "Fee Amount", location: "In App / Relazionale" },
    "feeType": { label: "Fee Type", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "installmentsMax": { label: "Installments Max", location: "In App / Relazionale" },
    "isActive": { label: "Is Active", location: "In App / Relazionale" },
    "providerName": { label: "Provider Name", location: "In App / Relazionale" },
    "rangeMax": { label: "Range Max", location: "In App / Relazionale" },
    "rangeMin": { label: "Range Min", location: "In App / Relazionale" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
  },
  "teamDocuments": {
    "caricatoDa": { label: "Caricato Da", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isCurrent": { label: "Is Current", location: "In App / Relazionale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "scadenza": { label: "Scadenza", location: "In App / Relazionale" },
    "tipo": { label: "Tipo", location: "In App / Relazionale" },
    "titolo": { label: "Titolo", location: "In App / Relazionale" },
    "visibileDipendente": { label: "Visibile Dipendente", location: "In App / Relazionale" },
  },
  "teamShiftTemplates": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "employeeId": { label: "ID Dipendente (Relazione)", location: "Gestione Team" },
    "giornoSettimana": { label: "Giorno Settimana", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "note": { label: "Note", location: "In App / Relazionale" },
    "oraFine": { label: "Ora Fine", location: "In App / Relazionale" },
    "oraInizio": { label: "Ora Inizio", location: "In App / Relazionale" },
    "postazione": { label: "Postazione", location: "In App / Relazionale" },
    "settimanaTipo": { label: "Settimana Tipo", location: "In App / Relazionale" },
  },
  "teamShifts": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isAttendanceVerified": { label: "Is Attendance Verified", location: "In App / Relazionale" },
    "locationId": { label: "Location  ID", location: "In App / Relazionale" },
    "shiftEnd": { label: "Shift End", location: "In App / Relazionale" },
    "shiftStart": { label: "Shift Start", location: "In App / Relazionale" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
    "userId": { label: "ID Autore (Relazione)", location: "Collegamento Operatore" },
  },
  "bookingServices": {
    "active": { label: "Attivo?", location: "Flag Visibilità" },
    "categoryId": { label: "Category  ID", location: "In App / Relazionale" },
    "color": { label: "Colore UI", location: "Personalizzazione Grafica" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "description": { label: "Descrizione", location: "Campo Testuale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "price": { label: "Prezzo", location: "Logica Finanziaria" },
  },
  "priceLists": {
    "active": { label: "Attivo?", location: "Flag Visibilità" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
    "validFrom": { label: "Valid From", location: "In App / Relazionale" },
    "validTo": { label: "Valid To", location: "In App / Relazionale" },
  },
  "quotes": {
    "active": { label: "Attivo?", location: "Flag Visibilità" },
    "amount": { label: "Importo", location: "Logica Finanziaria" },
    "category": { label: "Category", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "seasons": {
    "active": { label: "Attivo?", location: "Flag Visibilità" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "description": { label: "Descrizione", location: "Campo Testuale" },
    "endDate": { label: "End Date", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "startDate": { label: "Start Date", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "staffContractsCompliance": {
    "docType": { label: "Doc Type", location: "In App / Relazionale" },
    "docValue": { label: "Doc Value", location: "In App / Relazionale" },
    "expiresAt": { label: "Expires At", location: "In App / Relazionale" },
    "hasDoc": { label: "Has Doc", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "staffDocumentSignatures": {
    "docType": { label: "Doc Type", location: "In App / Relazionale" },
    "docVersion": { label: "Doc Version", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "method": { label: "Method", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "signedAt": { label: "Signed At", location: "In App / Relazionale" },
    "signedBy": { label: "Signed By", location: "In App / Relazionale" },
  },
  "teamCheckinEvents": {
    "device": { label: "Device", location: "In App / Relazionale" },
    "employeeId": { label: "ID Dipendente (Relazione)", location: "Gestione Team" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "note": { label: "Note", location: "In App / Relazionale" },
    "overrideAdmin": { label: "Override Admin", location: "In App / Relazionale" },
    "postazione": { label: "Postazione", location: "In App / Relazionale" },
    "timestamp": { label: "Timestamp", location: "In App / Relazionale" },
    "tipo": { label: "Tipo", location: "In App / Relazionale" },
  },
  "teamDocumentAlerts": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "dataAlert": { label: "Data Alert", location: "In App / Relazionale" },
    "documentId": { label: "Document  ID", location: "In App / Relazionale" },
    "employeeId": { label: "ID Dipendente (Relazione)", location: "Gestione Team" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "inviatoAt": { label: "Inviato At", location: "In App / Relazionale" },
    "risolto": { label: "Risolto", location: "In App / Relazionale" },
    "tipo": { label: "Tipo", location: "In App / Relazionale" },
  },
  "teamNotifications": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "dataRiferimento": { label: "Data Riferimento", location: "In App / Relazionale" },
    "employeeId": { label: "ID Dipendente (Relazione)", location: "Gestione Team" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "letta": { label: "Letta", location: "In App / Relazionale" },
    "messaggio": { label: "Messaggio", location: "In App / Relazionale" },
    "tipo": { label: "Tipo", location: "In App / Relazionale" },
    "titolo": { label: "Titolo", location: "In App / Relazionale" },
  },
  "userActivityLogs": {
    "action": { label: "Action", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "details": { label: "Details", location: "In App / Relazionale" },
    "entityId": { label: "Entity  ID", location: "In App / Relazionale" },
    "entityType": { label: "Entity Type", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "ipAddress": { label: "Ip Address", location: "In App / Relazionale" },
    "userId": { label: "ID Autore (Relazione)", location: "Collegamento Operatore" },
  },
  "userSessionSegments": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "durataMinuti": { label: "Durata Minuti", location: "In App / Relazionale" },
    "endedAt": { label: "Ended At", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "lastHeartbeatAt": { label: "Last Heartbeat At", location: "In App / Relazionale" },
    "startedAt": { label: "Started At", location: "In App / Relazionale" },
    "tipo": { label: "Tipo", location: "In App / Relazionale" },
    "userId": { label: "ID Autore (Relazione)", location: "Collegamento Operatore" },
  },
  "accessLogs": {
    "accessTime": { label: "Access Time", location: "In App / Relazionale" },
    "accessType": { label: "Access Type", location: "In App / Relazionale" },
    "barcode": { label: "Barcode", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "membershipStatus": { label: "Membership Status", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
  },
  "auditLogs": {
    "action": { label: "Action", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "details": { label: "Details", location: "In App / Relazionale" },
    "entityId": { label: "Entity  ID", location: "In App / Relazionale" },
    "entityType": { label: "Entity Type", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "performedBy": { label: "Performed By", location: "In App / Relazionale" },
  },
  "costCenters": {
    "code": { label: "Code", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "description": { label: "Descrizione", location: "Campo Testuale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isActive": { label: "Is Active", location: "In App / Relazionale" },
    "label": { label: "Label", location: "In App / Relazionale" },
    "tenantId": { label: "ID Tenant (Multisito)", location: "Logica Multi-tenant" },
  },
  "customLists": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "description": { label: "Descrizione", location: "Campo Testuale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "linkedActivities": { label: "Linked Activities", location: "In App / Relazionale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "systemCode": { label: "System Code", location: "In App / Relazionale" },
    "systemName": { label: "System Name", location: "In App / Relazionale" },
  },
  "importConfigs": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "entityType": { label: "Entity Type", location: "In App / Relazionale" },
    "fieldMapping": { label: "Field Mapping", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "importKey": { label: "Import Key", location: "In App / Relazionale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "sourceType": { label: "Source Type", location: "In App / Relazionale" },
  },
  "notifications": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isRead": { label: "Is Read", location: "In App / Relazionale" },
    "message": { label: "Message", location: "In App / Relazionale" },
    "title": { label: "Title", location: "In App / Relazionale" },
    "type": { label: "Type", location: "In App / Relazionale" },
    "userId": { label: "ID Autore (Relazione)", location: "Collegamento Operatore" },
  },
  "priceListItems": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "entityId": { label: "Entity  ID", location: "In App / Relazionale" },
    "entityType": { label: "Entity Type", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "price": { label: "Prezzo", location: "Logica Finanziaria" },
    "priceListId": { label: "Price List  ID", location: "In App / Relazionale" },
    "quoteId": { label: "Quote  ID", location: "In App / Relazionale" },
  },
  "teamActivityTypes": {
    "attivo": { label: "Attivo", location: "In App / Relazionale" },
    "categoria": { label: "Categoria", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "label": { label: "Label", location: "In App / Relazionale" },
    "sortOrder": { label: "Ordine (Ordinamento)", location: "Visualizzazione Elenchi" },
    "team": { label: "Team", location: "In App / Relazionale" },
  },
  "teamPostazioni": {
    "attiva": { label: "Attiva", location: "In App / Relazionale" },
    "colore": { label: "Colore", location: "In App / Relazionale" },
    "contaOre": { label: "Conta Ore", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "nome": { label: "Nome", location: "In App / Relazionale" },
    "ordine": { label: "Ordine", location: "In App / Relazionale" },
  },
  "teamWeekAssignments": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isManualOverride": { label: "Is Manual Override", location: "In App / Relazionale" },
    "note": { label: "Note", location: "In App / Relazionale" },
    "settimana": { label: "Settimana", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
    "weekStart": { label: "Week Start", location: "In App / Relazionale" },
  },
  "tenants": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "customMenuConfig": { label: "Custom Menu Config", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "logoUrl": { label: "Logo Url", location: "In App / Relazionale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "primaryColor": { label: "Primary Color", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "todos": {
    "completed": { label: "Completed", location: "In App / Relazionale" },
    "completedAt": { label: "Completed At", location: "In App / Relazionale" },
    "completedBy": { label: "Completed By", location: "In App / Relazionale" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "createdBy": { label: "Created By", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "text": { label: "Text", location: "In App / Relazionale" },
  },
  "activityStatuses": {
    "active": { label: "Attivo?", location: "Flag Visibilità" },
    "color": { label: "Colore UI", location: "Personalizzazione Grafica" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "sortOrder": { label: "Ordine (Ordinamento)", location: "Visualizzazione Elenchi" },
  },
  "agreementMonthlyOverrides": {
    "agreementId": { label: "Agreement  ID", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "month": { label: "Month", location: "In App / Relazionale" },
    "notes": { label: "Note", location: "Campo Testuale Libero" },
    "overrideAmount": { label: "Override Amount", location: "In App / Relazionale" },
    "seasonId": { label: "Season  ID", location: "In App / Relazionale" },
  },
  "customListItems": {
    "active": { label: "Attivo?", location: "Flag Visibilità" },
    "color": { label: "Colore UI", location: "Personalizzazione Grafica" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "listId": { label: "List  ID", location: "In App / Relazionale" },
    "sortOrder": { label: "Ordine (Ordinamento)", location: "Visualizzazione Elenchi" },
    "value": { label: "Value", location: "In App / Relazionale" },
  },
  "enrollmentDetails": {
    "active": { label: "Attivo?", location: "Flag Visibilità" },
    "color": { label: "Colore UI", location: "Personalizzazione Grafica" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "sortOrder": { label: "Ordine (Ordinamento)", location: "Visualizzazione Elenchi" },
  },
  "knowledge": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "descrizione": { label: "Descrizione", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "sezione": { label: "Sezione", location: "In App / Relazionale" },
    "titolo": { label: "Titolo", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "messages": {
    "content": { label: "Content", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isRead": { label: "Is Read", location: "In App / Relazionale" },
    "receiverId": { label: "Receiver  ID", location: "In App / Relazionale" },
    "senderId": { label: "Sender  ID", location: "In App / Relazionale" },
    "timestamp": { label: "Timestamp", location: "In App / Relazionale" },
  },
  "participantTypes": {
    "active": { label: "Attivo?", location: "Flag Visibilità" },
    "color": { label: "Colore UI", location: "Personalizzazione Grafica" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "sortOrder": { label: "Ordine (Ordinamento)", location: "Visualizzazione Elenchi" },
  },
  "paymentMethods": {
    "active": { label: "Attivo?", location: "Flag Visibilità" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "description": { label: "Descrizione", location: "Campo Testuale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "paymentNotes": {
    "active": { label: "Attivo?", location: "Flag Visibilità" },
    "color": { label: "Colore UI", location: "Personalizzazione Grafica" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "sortOrder": { label: "Ordine (Ordinamento)", location: "Visualizzazione Elenchi" },
  },
  "userRoles": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "description": { label: "Descrizione", location: "Campo Testuale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "permissions": { label: "Permissions", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
  },
  "cities": {
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "istatCode": { label: "Istat Code", location: "In App / Relazionale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "postalCode": { label: "Postal Code", location: "In App / Relazionale" },
    "provinceId": { label: "Province  ID", location: "In App / Relazionale" },
  },
  "memberDuplicateExclusions": {
    "excludedAt": { label: "Excluded At", location: "In App / Relazionale" },
    "excludedBy": { label: "Excluded By", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "memberId1": { label: "Member Id1", location: "In App / Relazionale" },
    "memberId2": { label: "Member Id2", location: "In App / Relazionale" },
  },
  "memberRelationships": {
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "memberId": { label: "ID Utente (Relazione)", location: "Collegamento TabAnagrafica" },
    "relatedMemberId": { label: "Related Member  ID", location: "In App / Relazionale" },
    "relationshipType": { label: "Relationship Type", location: "In App / Relazionale" },
  },
  "provinces": {
    "code": { label: "Code", location: "In App / Relazionale" },
    "countryId": { label: "Country  ID", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
    "region": { label: "Region", location: "In App / Relazionale" },
  },
  "subscriptionTypes": {
    "active": { label: "Attivo?", location: "Flag Visibilità" },
    "createdAt": { label: "Data Creazione", location: "Log di Sistema" },
    "description": { label: "Descrizione", location: "Campo Testuale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
  },
  "countries": {
    "code": { label: "Code", location: "In App / Relazionale" },
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "isDefault": { label: "Is Default", location: "In App / Relazionale" },
    "name": { label: "Nome", location: "Identificativo Principale" },
  },
  "systemConfigs": {
    "id": { label: "ID Univoco", location: "Sistema Centrale" },
    "keyName": { label: "Key Name", location: "In App / Relazionale" },
    "updatedAt": { label: "Data Aggiornamento", location: "Log di Sistema" },
    "value": { label: "Value", location: "In App / Relazionale" },
  },
  "sessions": {
    "expire": { label: "Expire", location: "In App / Relazionale" },
    "sess": { label: "Sess", location: "In App / Relazionale" },
    "sid": { label: "Sid", location: "In App / Relazionale" },
  },
};
