import { db } from "./db";
import { countries, provinces, cities } from "@shared/schema";

const ITALIAN_PROVINCES = [
  { code: "AG", name: "Agrigento", region: "Sicilia" },
  { code: "AL", name: "Alessandria", region: "Piemonte" },
  { code: "AN", name: "Ancona", region: "Marche" },
  { code: "AO", name: "Aosta", region: "Valle d'Aosta" },
  { code: "AR", name: "Arezzo", region: "Toscana" },
  { code: "AP", name: "Ascoli Piceno", region: "Marche" },
  { code: "AT", name: "Asti", region: "Piemonte" },
  { code: "AV", name: "Avellino", region: "Campania" },
  { code: "BA", name: "Bari", region: "Puglia" },
  { code: "BT", name: "Barletta-Andria-Trani", region: "Puglia" },
  { code: "BL", name: "Belluno", region: "Veneto" },
  { code: "BN", name: "Benevento", region: "Campania" },
  { code: "BG", name: "Bergamo", region: "Lombardia" },
  { code: "BI", name: "Biella", region: "Piemonte" },
  { code: "BO", name: "Bologna", region: "Emilia-Romagna" },
  { code: "BZ", name: "Bolzano", region: "Trentino-Alto Adige" },
  { code: "BS", name: "Brescia", region: "Lombardia" },
  { code: "BR", name: "Brindisi", region: "Puglia" },
  { code: "CA", name: "Cagliari", region: "Sardegna" },
  { code: "CL", name: "Caltanissetta", region: "Sicilia" },
  { code: "CB", name: "Campobasso", region: "Molise" },
  { code: "CE", name: "Caserta", region: "Campania" },
  { code: "CT", name: "Catania", region: "Sicilia" },
  { code: "CZ", name: "Catanzaro", region: "Calabria" },
  { code: "CH", name: "Chieti", region: "Abruzzo" },
  { code: "CO", name: "Como", region: "Lombardia" },
  { code: "CS", name: "Cosenza", region: "Calabria" },
  { code: "CR", name: "Cremona", region: "Lombardia" },
  { code: "KR", name: "Crotone", region: "Calabria" },
  { code: "CN", name: "Cuneo", region: "Piemonte" },
  { code: "EN", name: "Enna", region: "Sicilia" },
  { code: "FM", name: "Fermo", region: "Marche" },
  { code: "FE", name: "Ferrara", region: "Emilia-Romagna" },
  { code: "FI", name: "Firenze", region: "Toscana" },
  { code: "FG", name: "Foggia", region: "Puglia" },
  { code: "FC", name: "Forlì-Cesena", region: "Emilia-Romagna" },
  { code: "FR", name: "Frosinone", region: "Lazio" },
  { code: "GE", name: "Genova", region: "Liguria" },
  { code: "GO", name: "Gorizia", region: "Friuli-Venezia Giulia" },
  { code: "GR", name: "Grosseto", region: "Toscana" },
  { code: "IM", name: "Imperia", region: "Liguria" },
  { code: "IS", name: "Isernia", region: "Molise" },
  { code: "SP", name: "La Spezia", region: "Liguria" },
  { code: "AQ", name: "L'Aquila", region: "Abruzzo" },
  { code: "LT", name: "Latina", region: "Lazio" },
  { code: "LE", name: "Lecce", region: "Puglia" },
  { code: "LC", name: "Lecco", region: "Lombardia" },
  { code: "LI", name: "Livorno", region: "Toscana" },
  { code: "LO", name: "Lodi", region: "Lombardia" },
  { code: "LU", name: "Lucca", region: "Toscana" },
  { code: "MC", name: "Macerata", region: "Marche" },
  { code: "MN", name: "Mantova", region: "Lombardia" },
  { code: "MS", name: "Massa-Carrara", region: "Toscana" },
  { code: "MT", name: "Matera", region: "Basilicata" },
  { code: "ME", name: "Messina", region: "Sicilia" },
  { code: "MI", name: "Milano", region: "Lombardia" },
  { code: "MO", name: "Modena", region: "Emilia-Romagna" },
  { code: "MB", name: "Monza e Brianza", region: "Lombardia" },
  { code: "NA", name: "Napoli", region: "Campania" },
  { code: "NO", name: "Novara", region: "Piemonte" },
  { code: "NU", name: "Nuoro", region: "Sardegna" },
  { code: "OR", name: "Oristano", region: "Sardegna" },
  { code: "PD", name: "Padova", region: "Veneto" },
  { code: "PA", name: "Palermo", region: "Sicilia" },
  { code: "PR", name: "Parma", region: "Emilia-Romagna" },
  { code: "PV", name: "Pavia", region: "Lombardia" },
  { code: "PG", name: "Perugia", region: "Umbria" },
  { code: "PU", name: "Pesaro e Urbino", region: "Marche" },
  { code: "PE", name: "Pescara", region: "Abruzzo" },
  { code: "PC", name: "Piacenza", region: "Emilia-Romagna" },
  { code: "PI", name: "Pisa", region: "Toscana" },
  { code: "PT", name: "Pistoia", region: "Toscana" },
  { code: "PN", name: "Pordenone", region: "Friuli-Venezia Giulia" },
  { code: "PZ", name: "Potenza", region: "Basilicata" },
  { code: "PO", name: "Prato", region: "Toscana" },
  { code: "RG", name: "Ragusa", region: "Sicilia" },
  { code: "RA", name: "Ravenna", region: "Emilia-Romagna" },
  { code: "RC", name: "Reggio Calabria", region: "Calabria" },
  { code: "RE", name: "Reggio Emilia", region: "Emilia-Romagna" },
  { code: "RI", name: "Rieti", region: "Lazio" },
  { code: "RN", name: "Rimini", region: "Emilia-Romagna" },
  { code: "RM", name: "Roma", region: "Lazio" },
  { code: "RO", name: "Rovigo", region: "Veneto" },
  { code: "SA", name: "Salerno", region: "Campania" },
  { code: "SS", name: "Sassari", region: "Sardegna" },
  { code: "SV", name: "Savona", region: "Liguria" },
  { code: "SI", name: "Siena", region: "Toscana" },
  { code: "SR", name: "Siracusa", region: "Sicilia" },
  { code: "SO", name: "Sondrio", region: "Lombardia" },
  { code: "SU", name: "Sud Sardegna", region: "Sardegna" },
  { code: "TA", name: "Taranto", region: "Puglia" },
  { code: "TE", name: "Teramo", region: "Abruzzo" },
  { code: "TR", name: "Terni", region: "Umbria" },
  { code: "TO", name: "Torino", region: "Piemonte" },
  { code: "TP", name: "Trapani", region: "Sicilia" },
  { code: "TN", name: "Trento", region: "Trentino-Alto Adige" },
  { code: "TV", name: "Treviso", region: "Veneto" },
  { code: "TS", name: "Trieste", region: "Friuli-Venezia Giulia" },
  { code: "UD", name: "Udine", region: "Friuli-Venezia Giulia" },
  { code: "VA", name: "Varese", region: "Lombardia" },
  { code: "VE", name: "Venezia", region: "Veneto" },
  { code: "VB", name: "Verbano-Cusio-Ossola", region: "Piemonte" },
  { code: "VC", name: "Vercelli", region: "Piemonte" },
  { code: "VR", name: "Verona", region: "Veneto" },
  { code: "VV", name: "Vibo Valentia", region: "Calabria" },
  { code: "VI", name: "Vicenza", region: "Veneto" },
  { code: "VT", name: "Viterbo", region: "Lazio" },
];

const ITALIAN_CITIES = [
  { name: "Roma", province: "RM", postalCode: "00100" },
  { name: "Milano", province: "MI", postalCode: "20100" },
  { name: "Napoli", province: "NA", postalCode: "80100" },
  { name: "Torino", province: "TO", postalCode: "10100" },
  { name: "Palermo", province: "PA", postalCode: "90100" },
  { name: "Genova", province: "GE", postalCode: "16100" },
  { name: "Bologna", province: "BO", postalCode: "40100" },
  { name: "Firenze", province: "FI", postalCode: "50100" },
  { name: "Bari", province: "BA", postalCode: "70100" },
  { name: "Catania", province: "CT", postalCode: "95100" },
  { name: "Venezia", province: "VE", postalCode: "30100" },
  { name: "Verona", province: "VR", postalCode: "37100" },
  { name: "Messina", province: "ME", postalCode: "98100" },
  { name: "Padova", province: "PD", postalCode: "35100" },
  { name: "Trieste", province: "TS", postalCode: "34100" },
  { name: "Taranto", province: "TA", postalCode: "74100" },
  { name: "Brescia", province: "BS", postalCode: "25100" },
  { name: "Parma", province: "PR", postalCode: "43100" },
  { name: "Prato", province: "PO", postalCode: "59100" },
  { name: "Modena", province: "MO", postalCode: "41100" },
  { name: "Reggio Calabria", province: "RC", postalCode: "89100" },
  { name: "Reggio Emilia", province: "RE", postalCode: "42100" },
  { name: "Perugia", province: "PG", postalCode: "06100" },
  { name: "Livorno", province: "LI", postalCode: "57100" },
  { name: "Ravenna", province: "RA", postalCode: "48100" },
  { name: "Cagliari", province: "CA", postalCode: "09100" },
  { name: "Foggia", province: "FG", postalCode: "71100" },
  { name: "Rimini", province: "RN", postalCode: "47900" },
  { name: "Salerno", province: "SA", postalCode: "84100" },
  { name: "Ferrara", province: "FE", postalCode: "44100" },
  { name: "Sassari", province: "SS", postalCode: "07100" },
  { name: "Latina", province: "LT", postalCode: "04100" },
  { name: "Giugliano in Campania", province: "NA", postalCode: "80014" },
  { name: "Monza", province: "MB", postalCode: "20900" },
  { name: "Siracusa", province: "SR", postalCode: "96100" },
  { name: "Pescara", province: "PE", postalCode: "65100" },
  { name: "Bergamo", province: "BG", postalCode: "24100" },
  { name: "Forlì", province: "FC", postalCode: "47100" },
  { name: "Trento", province: "TN", postalCode: "38100" },
  { name: "Vicenza", province: "VI", postalCode: "36100" },
  { name: "Terni", province: "TR", postalCode: "05100" },
  { name: "Bolzano", province: "BZ", postalCode: "39100" },
  { name: "Novara", province: "NO", postalCode: "28100" },
  { name: "Piacenza", province: "PC", postalCode: "29100" },
  { name: "Ancona", province: "AN", postalCode: "60100" },
  { name: "Andria", province: "BT", postalCode: "76123" },
  { name: "Arezzo", province: "AR", postalCode: "52100" },
  { name: "Udine", province: "UD", postalCode: "33100" },
  { name: "Cesena", province: "FC", postalCode: "47521" },
  { name: "Lecce", province: "LE", postalCode: "73100" },
  { name: "Pesaro", province: "PU", postalCode: "61100" },
  { name: "Barletta", province: "BT", postalCode: "76121" },
  { name: "Alessandria", province: "AL", postalCode: "15121" },
  { name: "La Spezia", province: "SP", postalCode: "19100" },
  { name: "Pisa", province: "PI", postalCode: "56100" },
  { name: "Catanzaro", province: "CZ", postalCode: "88100" },
  { name: "Lucca", province: "LU", postalCode: "55100" },
  { name: "Brindisi", province: "BR", postalCode: "72100" },
  { name: "Treviso", province: "TV", postalCode: "31100" },
  { name: "Como", province: "CO", postalCode: "22100" },
  { name: "Busto Arsizio", province: "VA", postalCode: "21052" },
  { name: "Marsala", province: "TP", postalCode: "91025" },
  { name: "Grosseto", province: "GR", postalCode: "58100" },
  { name: "Varese", province: "VA", postalCode: "21100" },
  { name: "Caserta", province: "CE", postalCode: "81100" },
  { name: "Asti", province: "AT", postalCode: "14100" },
  { name: "Ragusa", province: "RG", postalCode: "97100" },
  { name: "L'Aquila", province: "AQ", postalCode: "67100" },
  { name: "Cremona", province: "CR", postalCode: "26100" },
  { name: "Pavia", province: "PV", postalCode: "27100" },
  { name: "Massa", province: "MS", postalCode: "54100" },
  { name: "Trapani", province: "TP", postalCode: "91100" },
  { name: "Cosenza", province: "CS", postalCode: "87100" },
  { name: "Potenza", province: "PZ", postalCode: "85100" },
  { name: "Viterbo", province: "VT", postalCode: "01100" },
  { name: "Savona", province: "SV", postalCode: "17100" },
  { name: "Benevento", province: "BN", postalCode: "82100" },
  { name: "Caltanissetta", province: "CL", postalCode: "93100" },
  { name: "Agrigento", province: "AG", postalCode: "92100" },
  { name: "Cuneo", province: "CN", postalCode: "12100" },
  { name: "Chieti", province: "CH", postalCode: "66100" },
  { name: "Teramo", province: "TE", postalCode: "64100" },
  { name: "Avellino", province: "AV", postalCode: "83100" },
  { name: "Siena", province: "SI", postalCode: "53100" },
  { name: "Rovigo", province: "RO", postalCode: "45100" },
  { name: "Pordenone", province: "PN", postalCode: "33170" },
  { name: "Campobasso", province: "CB", postalCode: "86100" },
  { name: "Aosta", province: "AO", postalCode: "11100" },
  { name: "Mantova", province: "MN", postalCode: "46100" },
  { name: "Lodi", province: "LO", postalCode: "26900" },
  { name: "Lecco", province: "LC", postalCode: "23900" },
  { name: "Matera", province: "MT", postalCode: "75100" },
  { name: "Rieti", province: "RI", postalCode: "02100" },
  { name: "Belluno", province: "BL", postalCode: "32100" },
  { name: "Biella", province: "BI", postalCode: "13900" },
  { name: "Vercelli", province: "VC", postalCode: "13100" },
  { name: "Frosinone", province: "FR", postalCode: "03100" },
  { name: "Gorizia", province: "GO", postalCode: "34170" },
  { name: "Imperia", province: "IM", postalCode: "18100" },
  { name: "Isernia", province: "IS", postalCode: "86170" },
  { name: "Macerata", province: "MC", postalCode: "62100" },
  { name: "Nuoro", province: "NU", postalCode: "08100" },
  { name: "Oristano", province: "OR", postalCode: "09170" },
  { name: "Pistoia", province: "PT", postalCode: "51100" },
  { name: "Sondrio", province: "SO", postalCode: "23100" },
  { name: "Verbania", province: "VB", postalCode: "28922" },
  { name: "Crotone", province: "KR", postalCode: "88900" },
  { name: "Vibo Valentia", province: "VV", postalCode: "89900" },
  { name: "Enna", province: "EN", postalCode: "94100" },
  { name: "Fermo", province: "FM", postalCode: "63900" },
  { name: "Ascoli Piceno", province: "AP", postalCode: "63100" },
  { name: "Trani", province: "BT", postalCode: "76125" },
];

export async function seedLocations() {
  console.log("Seeding locations...");
  
  const existingCountries = await db.select().from(countries);
  if (existingCountries.length > 0) {
    console.log("Locations already seeded, skipping...");
    return;
  }

  const [italy] = await db.insert(countries).values({
    code: "IT",
    name: "Italia",
    isDefault: true,
  }).returning();
  console.log(`Created country: ${italy.name}`);

  const provinceMap = new Map<string, number>();
  for (const prov of ITALIAN_PROVINCES) {
    const [inserted] = await db.insert(provinces).values({
      code: prov.code,
      name: prov.name,
      region: prov.region,
      countryId: italy.id,
    }).returning();
    provinceMap.set(prov.code, inserted.id);
  }
  console.log(`Created ${ITALIAN_PROVINCES.length} provinces`);

  for (const city of ITALIAN_CITIES) {
    const provinceId = provinceMap.get(city.province);
    if (provinceId) {
      await db.insert(cities).values({
        name: city.name,
        provinceId,
        postalCode: city.postalCode,
      });
    }
  }
  console.log(`Created ${ITALIAN_CITIES.length} cities`);
  
  console.log("Location seeding complete!");
}

seedLocations()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Seeding failed:", err);
    process.exit(1);
  });
